const constantsBreed = {
  FETCH_BREED: 'FETCH_BREED',
  FETCH_BREED_SUCCESS: 'FETCH_BREED_SUCCESS',
  LOAD_BREED_SUCCESS: 'LOAD_BREED_SUCCESS',
  ERROR_LOAD_BREED_SUCCESS: 'ERROR_LOAD_BREED_SUCCESS',
  FETCH_SUB_BREED_SUCCESS: 'FETCH_SUB_BREED_SUCCESS',
  FETCH_SUB_BREED: 'FETCH_SUB_BREED'
}

export default constantsBreed;
