const constantsBreedList = {
  FETCH_BREED_LIST: 'FETCH_BREED_LIST',
  FETCH_BREED_LIST_SUCCESS: 'FETCH_BREED_LIST_SUCCESS',
  LOAD_BREED_LIST_SUCCESS: 'LOAD_BREED_LIST_SUCCESS',
  ERROR_LOADING_SUCCESS: 'ERROR_LOADING_SUCCESS'
}

export default constantsBreedList;
